### ISSUE TITLE
Can't Connect The App to Firebase Database

### ISSUE THREAD

**Issue by AdityaRisangN** [dgewe/Chat-App-Android#1]
Hi dgewe! Nice too meet u on internet. Im trying to learn kotlin language from this application, but i got some problem. I cant connect the app to firebase database. I has  input the google-service.json to this project. Is that database like chat, users, etc created automatically when the app runs or I have to create it manually? Thanks u dgewe, Love from Indonesia :)
![ss](https://user-images.githubusercontent.com/88642141/128657511-aaf5f74e-96c2-48b4-b2ac-288b3856b8db.png)

**Comment by dgewe** [comment]
Hello, nice to meet you too!

Users can be created manually inside the app by navigating to the screen "Create Account".
Things like chats etc are created automatically when needed by the application.
