### ISSUE TITLE
Cannot query the value of property 'namespace' because configuration of project ':app' has not completed yet.

### ISSUE THREAD

**Issue by kramit912** [dgewe/Chat-App-Android#2]
Adding a Configuration as a dependency is a confusing behavior which isn't recommended. This behaviour has been deprecated and is scheduled to be removed in Gradle 8.0. If you're interested in inheriting the dependencies from the Configuration you are adding, you should use Configuration#extendsFrom instead

**Comment by dgewe** [comment]
Thank for letting me know, i'll look into it when I have time

**Comment by kramit912** [comment]
Thankyou for your time and response, i found this project pretty useful.
Though i'm a beginner in Android.
